version: "3.8"
services:

  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
      - "8008:8008"
    volumes:
      # ./dev/Caddyfile is where the config file is located
      - ./data/Caddyfile:/etc/caddy/Caddyfile

      # ./dev/certs is where the mkcert certificate is located
      - ./data/certs:/root/certs

      # persist Caddy's data in a volume
      - caddy_data:/data
      - caddy_config:/config

      # html static
      - ./data/www:/var/www

  fastapi:
    image: fastapi:v1
    volumes:
      - ../backend/:/backend/
    command: >
      bash -c "uvicorn backend.main:app --reload --port 8000  --host 0.0.0.0"
    ports:
      - 8000:8000
    container_name: fastapi
    stdin_open: true # docker run -i
    tty: true # docker run -t


volumes:
  caddy_data:
  caddy_config: